dist: trusty
language: bash
os:
    - linux
addons:
    apt:
        packages:
            - gnuplot

env:
    global:
        - NUM_BUILDS=1
        - GEN_GH=1
    matrix:
        - BUILD_ID=0

install:
    - cd $TRAVIS_BUILD_DIR;
    - scripts/setup_git.sh
    - make

script: 
    - cd $TRAVIS_BUILD_DIR;
    - scripts/run_valid.sh;
    - scripts/run_valid.sh small_llc;
    - scripts/run_valid.sh low_bandwidth;
    - scripts/run_valid.sh scramble_loads;
    - scripts/plot_valid.sh;

after_success:
    - cd $TRAVIS_BUILD_DIR;
    - scripts/atomic_push.sh;
