dist: trusty
language: bash

env:
    global:
        - NUM_BUILDS=1
        - GEN_GH=1
    matrix:
        - BUILD_ID=0

install:
    - cd $TRAVIS_BUILD_DIR;
    - make

script: 
    - cd $TRAVIS_BUILD_DIR;
    - rm -rf logs/*;
    - scripts/run_valid.sh $NUM_BUILDS $BUILD_ID;
    - scripts/plot_valid.sh;

after_success:
    - cd $TRAVIS_BUILD_DIR;
    - scripts/atomic_push.sh;
