dist: trusty
language: bash
os:
    - linux
addons:
    apt:
        packages:
            - gnuplot

env:
    global:
        - NUM_BUILDS=1
        - GEN_GH=1
    matrix:
        - MODE=
        - MODE=small_llc
        - MODE=low_bandwidth
        - MODE=scramble_loads

install:
    - cd $TRAVIS_BUILD_DIR;
    - scripts/setup_git.sh
    - make

script: 
    - cd $TRAVIS_BUILD_DIR;
    - scripts/run_valid.sh $MODE;
    - scripts/plot_valid.sh;

after_success:
    - cd $TRAVIS_BUILD_DIR;
    - scripts/atomic_push.sh;
