dist: trusty
language: bash
os:
    - linux
addons:
    apt:
        packages:
            - gnuplot

env:
    global:
        - NUM_BUILDS=1
        - GEN_GH=1
    matrix:
        - MODE=
        - MODE=small_llc
        - MODE=low_bandwidth
        - MODE=scramble_loads

install:
    - cd $TRAVIS_BUILD_DIR;
    - scripts/setup_git.sh
    - if [ "$TRAVIS_BRANCH" = "master" ]; then make; fi

script: 
    - cd $TRAVIS_BUILD_DIR;
    - if [ "$TRAVIS_BRANCH" = "master" ]; then scripts/run_valid.sh $MODE; fi
    - if [ "$TRAVIS_BRANCH" = "last_state" ] && [ -z "$MODE" ]; then scripts/plot_valid.sh; fi

after_success:
    - cd $TRAVIS_BUILD_DIR;
    - if [ "$TRAVIS_BRANCH" = "master" ] || [ -z "$MODE" ]; then scripts/atomic_push.sh; fi
