dist: trusty
language: bash

env:
    global:
        - NUM_BUILDS=4
    matrix:
        - BUILD_ID=0
        - BUILD_ID=1
        - BUILD_ID=2
        - BUILD_ID=3

install:
    - cd $TRAVIS_BUILD_DIR;
    - make

script: 
    - cd $TRAVIS_BUILD_DIR;
    - scripts/run_valid.sh $NUM_BUILDS $BUILD_ID;

deploy:
    skip_cleanup: true
    - cd $TRAVIS_BUILD_DIR;
    - scripts/atomic_push.sh
