#!/bin/bash

REPOROOT=$(git rev-parse --show-toplevel)
VALID_FILE=$REPOROOT/valid_prefetchers
BIN_FOLDER=$REPOROOT/bin
TRACE_FOLDER=$REPOROOT/traces
LOG_FOLDER=$REPOROOT/logs

PREF_PATH=$1
TRACE_PATH=$2
CONFIG=$3

echo "Pref path: $PREF_PATH"
echo "Trace path: $TRACE_PATH"

if [ -z "$PREF_PATH" ]; then
    echo "Usage: run prefetcher trace"
    echo -e "\tMissing prefetcher"
    exit 1
fi

if [ -z "$TRACE_PATH" ]; then
    echo "Usage: run prefetcher trace"
    echo -e "\tMissing trace"
    exit 1
fi

if [ ! -f "$PREF_PATH" ]; then
    echo -e "\tPrefetcher file does not exist\n"
    exit 1
fi

if [ ! -f "$TRACE_PATH" ]; then
    echo -e "\tTrace file does not exist\n"
    exit 1
fi

config_flag="-$CONFIG"
if [ -z "$CONFIG" ]; then
    config_flag=""
    CONFIG="base"
fi

sim=$(basename -- "$PREF_PATH")
sim="$(sed "s/\(.*\)_prefetcher.c/\1/g" <<<$sim)"

tr=$(basename -- "$TRACE_PATH")
tr=${tr%.*}

cd $REPOROOT
make $sim

if [ ! -d $LOG_FOLDER/$CONFIG ]; then
    mkdir $LOG_FOLDER/$CONFIG
fi
if [ ! -d $LOG_FOLDER/$CONFIG/$tr ]; then
    mkdir $LOG_FOLDER/$CONFIG/$tr
fi

echo "Running $sim <- $tr [$CONFIG]"
zcat $TRACE_FOLDER/$tr | $BIN_FOLDER/$sim -warmup_instructions 0 $config_flag> "$LOG_FOLDER/$CONFIG/$tr/$sim.log"
